In [1]:
import pandas as pd
import sqlite3
import numpy as np 

DB_PATH = '../backend/data.db'

conn = sqlite3.Connection(DB_PATH)

In [20]:
# Top 10%
pd.read_sql("""
    select article_id
    from articles 
    where 
        count > 150 
            
        and (length(title) - length(replace(title, ' ', ''))) / nullif(length(' '), 0) = 0
            
        and title not like "%-%"

    order by random() 
    limit 1
            
""", conn)

   article_id
0    19653842

In [4]:
pd.read_sql("""
    select *
    from articles
    where article_id == 11973479
""", conn)

   article_id  title clean_title                                  url  count
0    11973479  DSM-5       dsm-5  https://en.wikipedia.org/wiki/DSM-5    157