In [3]:
import pandas as pd
import sqlite3

conn = sqlite3.Connection('data.db')
cur = conn.cursor()

try:
    cur.execute('create index if not exists idx_suggestions_article_id on suggestions(article_id);')
    cur.execute('create index if not exists idx_suggestions_count on suggestions(count);')
    conn.commit()

finally:
    conn.close()

In [12]:
import pandas as pd
import sqlite3

pd.read_sql('''
            select 
			    *
            from embeddings
            order by random()
            limit 500
''', sqlite3.Connection('data.db'))

,id,created,modified,sentence_id,summary_id,article_id,embedding
0,2466066,1771675303349,1771675303349,None,66,None,b'(\x81g\xbb\xfef\xc4\xbb<$6\xbc\x80\xa8\x11=\...
1,2182522,1771671594020,1771671594020,None,522,None,b'\x1as\xeb\xbc\x07\x9d\xc6<\xa4Q@\xbc\xde@\xd...
2,1292864,1771660010110,1771660010110,None,864,None,b'\xb2\xf1^\xbd\xd2\x18|=-\xb6&=\x91\x02q\xbd\...
3,2669537,1771677941691,1771677941691,None,537,None,b'\xafY\xc1<\x99P\xb3;=\x8c\xc1<~\xba\x00=\x0b...
4,753060,1771652990000,1771652990000,None,60,None,b'\x01\x16:>\x83&k\xbcP{\xbd\xbc\x1e\xb1\xf3\x...
...,...,...,...,...,...,...,...
495,2424973,1771674757594,1771674757594,None,973,None,"b'\x93\x17\x9e\xbd=[8=\x92P.9\xc1\xa3/=""g\xff\..."
496,3147435,1771684173074,1771684173074,None,435,None,b'w.\xe0\xbd\xf6\x9a5\xbd\xba\x07\xe8\xbc&|\x1...
497,2847476,1771680261925,1771680261925,None,476,None,b'\xbc\x96\xba=l\xff\xed\xbd:~\x99=e\xa0\xa9<\...
498,437319,1771648885354,1771648885354,None,319,None,b'\xea\x9f\xb4<\xf1\t`\xbdds\x96=\x9e\xd2O=\x9...
499,1067481,1771657080371,1771657080371,None,481,None,"b'\xcd\xbcI=\xcd\x13d\xbc""j\xa5\xbc\xb3X\xbc=\..."

In [20]:
import pandas as pd
import sqlite3

df = pd.read_sql('''
		select * from sentences join (
            select 
			    *
            from embeddings
            order by random()
            limit 500
        ) as sub on sub.sentence_id == sentences.id
''', sqlite3.Connection('data.db'))

df

,id,created,modified,sentence,tokens,article_id,id,created,modified,sentence_id,summary_id,article_id,embedding
0,763,1771560055275,1771560055275,A glass floor was installed on the first level...,42,Eiffel_Tower,1868763,1771667506999,1771667506999,763,763,None,b'\xc7\xb5\xf2<\x82O*=\xccl&\xbc\xfd\xc8\xaa=\...
1,984,1771560055741,1771560055741,The common ingredient in all types of sushi is...,40,Sushi,1871984,1771667545688,1771667545688,984,984,None,"b'\x92\xec\xbe\xbd\x8f,T\xbd\x8c^\\<`\xc9\x93=..."
2,113,1771560054124,1771560054124,The meaning of the name ice cream varies from ...,60,Ice_cream,1298113,1771660088405,1771660088405,113,113,None,b')\xa2\xc8<=\xf7\x8f\xbdL\xdc\xca<\x1e\xd7\xb...
3,114,1771560054124,1771560054124,Products that do not meet the criteria to be c...,44,Ice_cream,2251114,1771672495232,1771672495232,114,114,None,b'\xeb\xf6E=~\x14\x95\xbd\xc8I\xae<\xae\xf1\xa...
4,125,1771560054124,1771560054124,There is no evidence to support these legends....,56,Ice_cream,2668125,1771677928421,1771677928421,125,125,None,b'\x1b\x1c\xcd\xbc\xd1V\x1c=\xd6(I\xbd\n\x99\x...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,413,1771560054695,1771560054695,Hamburgers and veggie burgers served with chip...,40,Hamburger,574413,1771650665630,1771650665630,413,413,None,b'\xd1\xc0\x7f;E\x93\x0e\xbd\x8ce\xc4\xbb\xc1\...
496,10,1771560053971,1771560053971,"Afterwards, the ocean's current name was coine...",43,Pacific_Ocean,426010,1771648741880,1771648741880,10,10,None,b'\xe5C\xde\xbb\xe4\xb30=\xc2\x9eE\xbd\xb9\xb9...
497,479,1771560055036,1771560055036,"After Luna 24 in 1976, there were no soft land...",50,Moon_landing,212479,1771645987228,1771645987228,479,479,None,b'\xdf\x81\x96=\x84\xf8K\xbd:\x96\xae=\xac\x0b...
498,851,1771560055487,1771560055487,The Himalayas form most of the south-west port...,37,Himalayas,333851,1771647538204,1771647538204,851,851,None,b'\xf1\xe3a=\x85\x9cP\xbdXUA\xbd\x15M\xe5\xbbg...
499,130,1771560054124,1771560054124,Recipes for flavoured ices begin to appear in ...,33,Ice_cream,1742130,1771665865573,1771665865573,130,130,None,b'R\xa4\xd0\xbd\xfe\xbb\xbb\xbdP\x86\xfc<\xf3\...

In [19]:
conn = sqlite3.Connection('data.db')
cur = conn.cursor()
cur.execute('update embeddings set sentence_id = summary_id')
conn.commit()

In [10]:
import pandas as pd
import sqlite3

df = pd.read_sql('''
    select 
        unique_sentences.article_id, 
        link_count
    from (
        select distinct article_id
        from sentences
    ) as unique_sentences               
    join (
        select 
            article_id, 
            count(*) as link_count
        from (
            select distinct parent_article_id, article_id
            from links
        )
        group by article_id
    ) as link_counts
        on unique_sentences.article_id == link_counts.article_id
    left join summaries
        on unique_sentences.article_id == summaries.article_id
    where summaries.id is null

''', sqlite3.Connection('data.db'))

In [ ]:
import pandas as pd
import sqlite3

df = pd.read_sql('''
        select id, article_id
        from (
                select sentence_id from embeddings order by random() limit 1000) as embeddings
        join sentences on sentences.id == embeddings.sentence_id
''', sqlite3.Connection('data.db'))

df.sample(5)

      id    article_id
651  683  Eiffel_Tower
838  469          Taco
692  666  Eiffel_Tower
833  936     Himalayas
126  963         Sushi

In [7]:
df.sample()

         id                  article_id
237  380023  American_Revolutionary_War

In [2]:
import pandas as pd
import sqlite3

pd.read_sql('''
		select 
			sentence_id as chunk_id, 
			embedding as vector
		from embeddings
		join sentences
			on embeddings.sentence_id == sentences.id
		where sentences.article_id = "Taco" and sentences.id = 441
''', sqlite3.Connection('data.db'))

      chunk_id                                             vector
0          441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
1          441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
2          441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
3          441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
4          441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
...        ...                                                ...
3302       441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
3303       441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
3304       441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
3305       441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...
3306       441  b'\xb5H\x8b<\xb4i\xe9<!14\xbd\xf5\x8f]=\x1c^\x...

[3307 rows x 2 columns]

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.Connection('data.db')
cur = conn.cursor()

cur.execute('VACUUM ')
# cur.execute("PRAGMA wal_checkpoint(TRUNCATE);")

conn.commit()

In [5]:
import pandas as pd
import sqlite3

pd.read_sql('''
		select 
			article_id, 
			title, 
			clean_title,
			count
		from suggestions
''', sqlite3.Connection('data.db'))

,article_id,title,clean_title,count
0,&,Ampersand,ampersand,3
1,'Ala'_al-Din_al-Bukhari,'Ala' al-Din al-Bukhari,'ala' al-din al-bukhari,44
2,'Round_About_Midnight,'Round About Midnight,'round about midnight,4
3,'Til_There_Was_You,'Til There Was You,'til there was you,3
4,(Everything_I_Do)_I_Do_It_for_You,(Everything I Do) I Do It for You,(everything i do) i do it for you,160
...,...,...,...,...
29061,Ōkōchi_Masatada,Ōkōchi Masatada,Ōkōchi masatada,1
29062,Śrauta,Śrauta,Śrauta,694
29063,Śuddhodana,Śuddhodana,Śuddhodana,612
29064,Śāstra_pramāṇam_in_Hinduism,Śāstra pramāṇam,Śāstra pramāṇam,338
29065,ǂKá̦gára,ǂKá̦gára,ǂká̦gára,2

In [34]:
df.iloc[0]['sentence']

"After Renaissance, the power of the Pope to serve as an effective arbitrator was questioned, despite brief efforts to restore the same. While the Pope was still part of discussions in the 17th century CE, the effectiveness of Pope's arbitration declined."

In [14]:
import pandas as pd
import sqlite3

# 2,186,104 sentences
# 30K articles
# 72 sentences per article on average
df = pd.read_sql('''

    select *
    from sentences 
    order by random()
    limit 10000
    
''', sqlite3.Connection('data.db'))

In [28]:
samp = df.sample().iloc[0]
print(samp['article_id'])
print()
sen = samp['sentence'].split()
s = 0
while s + 15 < len(sen):
    print(' '.join(sen[s : s + 15]))
    s = s + 15
print(' '.join(sen[s :]))

Rutgers_University

In 1925, the mascot was changed to Chanticleer, a fighting rooster from the medieval fable
Reynard the Fox (Le Roman de Renart) which was used by Geoffrey Chaucer in the
Canterbury Tales.

In [2]:
import requests
from bs4 import BeautifulSoup

In [ ]:
def get_soup(href, session, sem):
    headers = {'User-Agent': 'MyApp/1.0 (you@example.com)'}
    url = f'https://en.wikipedia.org/w/rest.php/v1/page/{href}/html'
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, features="html.parser")
    print(f'Got soup for: {href}')
    return soup

In [7]:
soup = get_soup('Tom_Cruise', None, None)

Got soup for: Tom_Cruise

In [13]:
for elem in soup.find_all('img'):
    print(elem.get('src'))

//upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Tom_Cruise-2428.jpg/250px-Tom_Cruise-2428.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Tom_Cruise_signature.svg/250px-Tom_Cruise_signature.svg.png
//upload.wikimedia.org/wikipedia/commons/thumb/d/db/1985_Tom_Cruise.jpg/250px-1985_Tom_Cruise.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tom_cruise_1989.jpg/250px-Tom_cruise_1989.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/TomCruiseOct07.jpg/250px-TomCruiseOct07.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/2/24/Tom_Cruise_by_Gage_Skidmore.jpg/250px-Tom_Cruise_by_Gage_Skidmore.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Tom_Cruise_Sydney_Premiere_Mission_Impossible_part_one_%2853019353900%29_%28cropped%29.jpg/250px-Tom_Cruise_Sydney_Premiere_Mission_Impossible_part_one_%2853019353900%29_%28cropped%29.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Tom_Cruise_by_Gage_Skidmore_2.jpg/250px-Tom_Cruise_by_Gage_Skidmore_2.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/5/58/TomCruiseHWoFOct10.jpg/250px-TomCruiseHWoFOct10.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Plaque_with_Tom_Cruise%27s_handprints_in_Leicester_Sq_London.jpg/250px-Plaque_with_Tom_Cruise%27s_handprints_in_Leicester_Sq_London.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tom_Cruise_and_Mimi_Rogers_in_1989.jpg/250px-Tom_Cruise_and_Mimi_Rogers_in_1989.jpg
//upload.wikimedia.org/wikipedia/commons/thumb/2/24/Tom_Cruise_%26_Katie_Holmes_WHCAD.jpg/250px-Tom_Cruise_%26_Katie_Holmes_WHCAD.jpg
//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/20px-Commons-logo.svg.png
//upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wikinews-logo.svg/40px-Wikinews-logo.svg.png
//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Wikiquote-logo.svg/40px-Wikiquote-logo.svg.png
//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/40px-Wikidata-logo.svg.png
//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/20px-OOjs_UI_icon_edit-ltr-progressive.svg.png
//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/20px-OOjs_UI_icon_edit-ltr-progressive.svg.png

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.Connection('data.db')
cur = conn.cursor()

In [3]:
t = pd.read_sql(f'''
       select * from suggestions where count > 1000 order by random() limit 1
''', conn).iloc[0]['article_id']

with open('../backend/target.txt', 'wt') as file:
    file.write(t)

In [2]:
cur.execute('delete from embeddings')
conn.commit()

In [ ]:
s
t

,id,created,modified,sentence_id,summary_id,embedding
0,1,1771172757248,1771172757248,None,359,b'\x80\x04\x95\x8d\x06\x00\x00\x00\x00\x00\x00...

In [5]:
import numpy as np

np.frombytes(t.iloc[0]['embedding'])

AttributeError: module 'numpy' has no attribute 'frombytes'

In [ ]:
# t['embedding'] = t['embedding'].apply(lambda x: pickle.loads(x))

In [7]:
import numpy as np 
t['embedding'] = t['embedding'].apply(lambda x: array_to_blob(x))

In [11]:
data = [(x['id'], x['embedding']) for _, x in t[['id', 'embedding']].iterrows()]

In [12]:
cur.executemany(
    'update embeddings set embedding = ? where id = ?',
    data
)
conn.commit()

In [3]:
t = pd.read_sql(f'''
		select 
			* from embeddings limit 2
''', conn)
t['embedding'] = t['embedding'].apply(lambda x: pickle.loads(x))

In [6]:
t.iloc[0]['embedding'].dtype, t.iloc[0]['embedding'].shape

(dtype('float32'), (384,))

In [4]:
t = pd.read_sql(f'''
		select 
			article_id, 
			title, 
			title as clean_title,
			count(links.to_link) as count
		from summaries
		join links
			on links.to_link == summaries.article_id 
		group by article_id, title
            order by random()
            limit 100
''', conn)
t

,article_id,title,clean_title,count
0,Culture_industry,Culture industry,Culture industry,53
1,Pierre_de_Bérulle,Pierre de Bérulle,Pierre de Bérulle,105
2,Indian_country,Indian country,Indian country,90
3,Party_divisions_of_United_States_Congresses,Party divisions of United States Congresses,Party divisions of United States Congresses,48
4,Dan_Wilson_(musician),Dan Wilson (musician),Dan Wilson (musician),95
...,...,...,...,...
95,Cuban_dissident_movement,Cuban dissident movement,Cuban dissident movement,42
96,Roman_Syria,Roman Syria,Roman Syria,46
97,African_diaspora_religions,African diaspora religions,African diaspora religions,113
98,Old_Style_and_New_Style_dates,Old Style and New Style dates,Old Style and New Style dates,157
99,Whig_Party_(United_States),Whig Party (United States),Whig Party (United States),970

In [4]:
t = pd.read_sql(f'''
select *
      from summaries left join thumbnails using (article_id) where thumbnails.id is null
''', conn)
t

,id,created,modified,title,description,extract,article_id,id,created,modified,src,width,height
0,2,1771167529992,1771167529992,Libertarian socialism,Political philosophy,Libertarian socialism is an anti-authoritarian...,Libertarian_socialism,None,None,None,None,None,None
1,9,1771167530626,1771167530626,Anarchism,Political philosophy and movement,Anarchism is a political philosophy and moveme...,Anarchism,None,None,None,None,None,None
2,31,1771167532521,1771167532521,Family values,Cultural values based on traditional family st...,"Family values, sometimes referred to as famili...",Family_values,None,None,None,None,None,None
3,33,1771167532707,1771167532707,Critique of political economy,Social critique,Critique of political economy or simply the fi...,Critique_of_political_economy,None,None,None,None,None,None
4,45,1771167533771,1771167533771,Truman Doctrine,Anti-Soviet U.S. Cold War foreign policy,The Truman Doctrine is a U.S. foreign policy t...,Truman_Doctrine,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6252,26393,1771172425401,1771172425401,Save the Children,Non-government organization founded in 1919,"The Save the Children Fund, commonly known as ...",Save_the_Children,None,None,None,None,None,None
6253,26404,1771172427234,1771172427234,African Americans in Tennessee,Largest racial and ethnic minority in Tennesse...,African Americans are the second largest censu...,African_Americans_in_Tennessee,None,None,None,None,None,None
6254,26406,1771172427509,1771172427509,Insurgency in Balochistan,Insurgency in Iran and Pakistan,Baloch separatists and various Islamist milita...,Insurgency_in_Balochistan,None,None,None,None,None,None
6255,26409,1771172427967,1771172427967,Verstehen,Social science conception of understanding and...,"\nVerstehen, in the context of German philosop...",Verstehen,None,None,None,None,None,None
6256,26415,1771172428786,1771172428786,Pope Vigilius,Head of the Catholic Church from 537 to 555,Pope Vigilius was the bishop of Rome from 29 M...,Pope_Vigilius,None,None,None,None,None,None

In [18]:
article_id = 'Libertarian_socialism'
import requests
headers = {'User-Agent': 'MyApp/1.0 (you@example.com)'}
url = f'https://en.wikipedia.org/api/rest_v1/page/summary/{article_id}'

r = requests.get(url, headers=headers)
r.raise_for_status()
r.json()

{'type': 'standard',
 'title': 'Libertarian socialism',
 'displaytitle': '<span class="mw-page-title-main">Libertarian socialism</span>',
 'namespace': {'id': 0, 'text': ''},
 'wikibase_item': 'Q1852084',
 'titles': {'canonical': 'Libertarian_socialism',
  'normalized': 'Libertarian socialism',
  'display': '<span class="mw-page-title-main">Libertarian socialism</span>'},
 'pageid': 18048,
 'lang': 'en',
 'dir': 'ltr',
 'revision': '1336912131',
 'tid': 'ebe2bdfc-034f-11f1-bff0-301a39a12ee1',
 'timestamp': '2026-02-06T11:35:22Z',
 'description': 'Political philosophy',
 'description_source': 'local',
 'content_urls': {'desktop': {'page': 'https://en.wikipedia.org/wiki/Libertarian_socialism',
   'revisions': 'https://en.wikipedia.org/wiki/Libertarian_socialism?action=history',
   'edit': 'https://en.wikipedia.org/wiki/Libertarian_socialism?action=edit',
   'talk': 'https://en.wikipedia.org/wiki/Talk:Libertarian_socialism'},
  'mobile': {'page': 'https://en.wikipedia.org/wiki/Libertarian_socialism',
   'revisions': 'https://en.wikipedia.org/wiki/Special:History/Libertarian_socialism',
   'edit': 'https://en.wikipedia.org/wiki/Libertarian_socialism?action=edit',
   'talk': 'https://en.wikipedia.org/wiki/Talk:Libertarian_socialism'}},
 'extract': "Libertarian socialism is an anti-authoritarian and anti-capitalist political current that emphasises self-governance and workers' self-management. It is contrasted from other forms of socialism by its rejection of state ownership and from other forms of libertarianism by its rejection of private property. Broadly defined, it includes schools of both anarchism and Marxism, as well as other tendencies that oppose the state and capitalism.",
 'extract_html': "<p><b>Libertarian socialism</b> is an anti-authoritarian and anti-capitalist political current that emphasises self-governance and workers' self-management. It is contrasted from other forms of socialism by its rejection of state ownership and from other forms of libertarianism by its rejection of private property. Broadly defined, it includes schools of both anarchism and Marxism, as well as other tendencies that oppose the state and capitalism.</p>"}

In [9]:
table = 'summaries'
t = pd.read_sql(f'''
select links.to_link, count(*)
            from links 
            left join {table}
                on {table}.article_id == links.to_link
            where {table}.article_id is null
            group by links.to_link
            order by count(*) desc
            limit 100
''', conn)
# print(t['title'])
# print(t['extract'])
t

                                         to_link  count(*)
0                                     Irene_Cara       183
1                                       R._Kelly       182
2                                          Ceuta       181
3                                    René_Girard       164
4                                Salmon_P._Chase       164
..                                           ...       ...
95  1976_Republican_Party_presidential_primaries       155
96           1988_Republican_National_Convention       155
97                           1990_FIFA_World_Cup       155
98                                      Actinide       155
99                                       Antwerp       155

[100 rows x 2 columns]

In [122]:
t = pd.read_sql('''
    select *
    from summaries
    join embeddings
        on summaries.id == embeddings.summary_id
    order by random()
    limit 1
''', conn).iloc[0]
# print(t['title'])
# print(t['extract'])

In [123]:
tvec = pickle.loads(t['embedding'])
tvec

array([ 2.02816390e-02, -9.45562944e-02,  6.61663478e-04,  8.30215495e-03,
        2.61283219e-02,  2.79981550e-02, -5.89590892e-02, -2.63574030e-02,
       -2.68014404e-03,  8.29881709e-03, -5.40959425e-02,  5.22493310e-02,
       -4.90091257e-02,  9.98159721e-02,  3.83512713e-02,  1.95561498e-02,
       -2.11518854e-02,  3.80759202e-02,  1.64228119e-02, -4.19834964e-02,
        5.44787534e-02,  4.75984663e-02, -1.40313413e-02,  6.10070415e-02,
        6.16732053e-02, -6.23113327e-02,  2.58560386e-02, -1.16589488e-02,
       -3.24173388e-03, -6.55190945e-02, -2.73302756e-02, -3.57118063e-02,
        5.14993407e-02, -4.79396135e-02, -1.67671982e-02, -7.11428002e-02,
       -3.28804441e-02, -5.60915610e-03,  1.01110870e-02,  5.95986331e-03,
       -9.76122357e-03,  1.66929848e-02, -4.51576401e-04,  1.66278786e-03,
       -2.79408004e-02,  2.82687657e-02, -2.72699855e-02,  1.65593170e-03,
        4.71234098e-02, -6.97898045e-02,  1.99317955e-03,  1.90988439e-03,
        2.97724307e-02,  1.35912284e-01, -9.44675952e-02, -8.91411502e-04,
       -3.38245109e-02,  5.71867898e-02,  4.61659394e-02, -5.49042597e-04,
        5.19477017e-03, -4.16476093e-02,  1.96428111e-04,  4.00602259e-02,
       -3.23619880e-02,  5.43320877e-03, -2.03953963e-02,  1.43852755e-01,
       -9.82268713e-03, -8.45858157e-02, -4.11125049e-02,  9.19032318e-04,
        1.36284623e-02, -1.51987057e-02,  3.36042382e-02,  2.78306864e-02,
        3.86937484e-02, -1.11193070e-03,  1.04448773e-01, -3.73101681e-02,
        7.18514919e-02, -9.38328877e-02,  5.28910793e-02,  2.07626317e-02,
       -1.10153377e-01,  1.86396651e-02, -5.68802934e-03, -8.67084488e-02,
       -7.43497983e-02,  1.67697575e-02,  9.26032942e-03,  4.19312902e-02,
       -6.68000579e-02, -4.37451527e-02,  2.51420904e-02, -2.99225692e-02,
       -2.52574459e-02, -8.10168162e-02,  2.00108998e-02,  3.56851891e-02,
        8.80653113e-02, -1.23991743e-02,  1.11176893e-02, -7.41899461e-02,
       -3.52387466e-02, -3.27683426e-02,  5.36862798e-02,  5.63172437e-02,
       -4.86660935e-03,  3.42533030e-02, -2.19974313e-02, -2.24033594e-02,
       -9.77435187e-02, -2.55471505e-02,  2.89385784e-02, -2.71094162e-02,
        1.07546765e-02,  7.88927898e-02, -8.17227177e-03,  2.16990598e-02,
        5.93778975e-02,  3.52270454e-02, -1.62320640e-02, -4.48150560e-02,
        9.87752061e-03, -1.31213460e-02,  1.16513707e-02, -3.08689792e-02,
       -5.92451869e-03, -2.90943161e-02, -4.16471027e-02,  4.38193697e-03,
        6.37084991e-02,  1.17239989e-01,  6.37854412e-02,  7.26790577e-02,
       -1.65267084e-02, -1.91475172e-02,  1.53868673e-02, -5.46782799e-02,
       -1.53018693e-02,  4.82127704e-02, -4.45779413e-02, -3.67492773e-02,
       -9.00743753e-02, -3.75367142e-02,  4.58624661e-02,  5.11810556e-02,
       -2.90535912e-02,  4.22907919e-02, -2.08174419e-02, -1.55547997e-02,
       -1.01847552e-01, -6.40425533e-02,  8.34221095e-02, -1.36900283e-02,
        1.67197473e-02, -1.04867732e-02,  1.36317670e-01, -9.25896242e-02,
        3.34948325e-03, -1.99537370e-02, -1.11300331e-02, -3.55509333e-02,
        6.06436767e-02, -4.06073732e-03,  6.09272420e-02, -5.35945520e-02,
        3.01087350e-02, -4.40297537e-02,  3.54346894e-02, -7.37800787e-04,
        3.52215730e-02,  3.84649076e-02, -5.53618371e-02, -7.07067475e-02,
       -4.98773567e-02, -1.89877767e-02, -3.46024111e-02,  4.23454940e-02,
       -1.68823171e-02, -5.64140826e-02,  4.21612710e-02,  6.34055138e-02,
        1.33295413e-02,  6.65820986e-02, -2.08430402e-02, -1.16765141e-01,
       -8.77557881e-03, -5.19795977e-02, -4.88811731e-02,  3.33729945e-02,
        1.73194483e-02, -1.09993450e-01,  2.33808402e-02, -1.97963696e-02,
       -2.36052852e-02, -1.00885175e-01, -1.75955407e-02, -2.35404097e-03,
       -1.56894494e-02, -2.05337163e-02,  9.05560181e-02,  3.51088196e-02,
       -7.23999664e-02, -3.25233229e-02, -2.01615673e-02,  9.57380012e-02,
        1.31879877e-02, -1.50581701e-02,  3.51572107e-03,  6.24046773e-02,
       -1.84668414e-02, -2.60591973e-02,  2.56300420e-02,  4.33733640e-03,
       -2.28517521e-02, -6.30735327e-03,  5.32334903e-03,  6.37165084e-02,
       -1.59722101e-02,  1.37049660e-01,  7.99042583e-02,  1.84819909e-33,
       -2.19892375e-02,  3.05215400e-02, -2.29250453e-02,  7.15876296e-02,
        6.50523230e-02, -3.01644988e-02,  1.51950493e-02,  6.42170664e-03,
        2.33958829e-02, -2.07443275e-02, -1.43763525e-02, -5.05939685e-02,
       -5.09513244e-02, -2.79328804e-02, -2.32528467e-02,  1.09354919e-02,
       -3.06007499e-03, -5.40928282e-02,  3.31022628e-02, -8.80434811e-02,
        3.30150872e-02,  6.92971125e-02, -2.28581466e-02, -6.92697018e-02,
        1.45150021e-01, -1.50641918e-01,  2.48587616e-02,  1.14115968e-01,
        1.79540087e-03, -4.39438038e-03, -3.04692774e-03,  6.98396116e-02,
        8.67370442e-02,  3.30845565e-02, -1.15563255e-02,  7.47537464e-02,
        4.90641408e-02,  1.61274280e-02, -4.27764393e-02, -2.68689189e-02,
        2.23175948e-03, -1.27850752e-02, -6.38535768e-02, -2.09295135e-02,
       -8.15605968e-02, -4.98084016e-02,  2.46833973e-02,  7.82347247e-02,
       -3.78371291e-02, -1.68061629e-02, -3.94180529e-02,  3.65641899e-02,
       -2.87404656e-02, -1.52776584e-01, -4.47898544e-02, -2.03672750e-03,
        8.34686831e-02,  3.99958948e-03, -2.25333273e-02, -4.59647290e-02,
        8.20350051e-02,  1.53066777e-03,  1.73294486e-03,  4.97281961e-02,
        3.58965844e-02,  7.75322318e-02, -3.00493967e-02,  1.28718004e-01,
       -2.22871657e-02,  4.41460423e-02,  1.20558320e-02,  2.69422643e-02,
       -7.36969709e-02,  5.25324792e-02, -4.32102978e-02,  5.61292395e-02,
       -4.95009236e-02, -2.74877157e-02, -8.92182067e-02,  6.01067767e-02,
       -5.92341125e-02, -5.05349413e-02,  4.98382002e-02, -1.08499452e-02,
        3.46208401e-02, -4.01959405e-04,  4.99816425e-02, -8.36087950e-03,
       -6.15025535e-02,  2.92870402e-02,  3.71806659e-02, -5.86590469e-02,
       -5.19586094e-02,  9.16965585e-03,  9.63844825e-04,  5.42413883e-32,
       -1.47415674e-03, -8.88426527e-02, -8.02009553e-02, -2.41767485e-02,
        6.33383542e-02,  2.29859073e-02,  1.78781990e-02, -1.73826031e-02,
       -8.36184062e-03, -2.34300531e-02,  9.46132001e-03, -3.17949541e-02,
       -7.56534263e-02,  1.57271326e-01,  2.00186260e-02, -3.01890485e-02,
       -4.45619598e-02,  2.86288168e-02, -2.18385743e-04,  1.89591257e-03,
        8.32490623e-02,  1.35003859e-02,  1.58435684e-02,  1.20195830e-02,
       -5.90195470e-02, -8.16985071e-02,  4.84933052e-03,  1.21197440e-01,
        3.11617646e-02, -1.27847157e-02, -3.75017598e-02,  1.68073680e-02,
        6.60312688e-03, -8.11637565e-02,  4.31223288e-02,  1.79338455e-02,
       -1.45964902e-02, -5.29309437e-02,  9.15395189e-03,  7.72169158e-02,
        1.07905408e-02, -4.44741640e-03,  7.37020895e-02,  5.53215970e-04,
        1.67775284e-02,  3.60899046e-03, -2.89499424e-02,  1.70668159e-02,
       -3.75699848e-02, -7.18310922e-02,  6.67570680e-02,  3.53667624e-02,
        6.63319454e-02, -8.26286301e-02,  4.81794067e-02, -6.22477978e-02,
        5.01460172e-02, -1.10828929e-01,  4.71879095e-02,  3.59253101e-02,
       -9.61642191e-02,  8.41651335e-02,  2.45268038e-03, -3.08488961e-02],
      dtype=float32)

In [212]:
t = pd.read_sql('''
    select *
    from summaries
    join embeddings
        on summaries.id == embeddings.summary_id
    where title like '%tv%'
    order by random()
    limit 1
''', conn).iloc[0]
print(t['title'])
print(t['extract'])
from scipy.spatial.distance import cosine
print(cosine(tvec, pickle.loads(t['embedding'])))

Apple TV (streaming service)
Apple TV, formerly known as Apple TV+, is a subscription over-the-top streaming service owned by Apple. The service launched on November 1, 2019, and it offers a selection of original production film and television series called Apple Originals. Its programming arm is Apple Studios.
0.6698301434516907

In [ ]:
# cur.execute('delete from embeddings')
# conn.commit()

In [23]:
pd.read_sql('''
    select 
        sources.source_link, 
        case when summaries.id is not null then True else False end as has_summary,
        count(links.from_link)
    from sources 
    left join summaries 
        using (source_link)
    left join links
        on sources.source_link == links.from_link
    group by sources.source_link
    order by count(links.from_link) desc
    limit 100
''', conn)

                 source_link  has_summary  count(links.from_link)
0               Conservatism            0                    8070
1            Catholic_Church            0                    4991
2                  Joe_Biden            1                    4629
3              Ronald_Reagan            1                    4503
4            John_F._Kennedy            0                    4450
..                       ...          ...                     ...
95                Bangladesh            1                    2535
96                  Holy_See            0                    2518
97                Korean_War            1                    2512
98              Roy_Halladay            1                    2507
99  People's_Liberation_Army            0                    2504

[100 rows x 3 columns]

In [25]:
headers = {'User-Agent': 'MyApp/1.0 (you@example.com)'}
source_link = 'Joe_Biden'
url = f'https://en.wikipedia.org/api/rest_v1/page/summary/{source_link}'

import requests 

r = requests.get(url, headers=headers)
r.raise_for_status()
r.json()

{'type': 'standard',
 'title': 'Joe Biden',
 'displaytitle': '<span class="mw-page-title-main">Joe Biden</span>',
 'namespace': {'id': 0, 'text': ''},
 'wikibase_item': 'Q6279',
 'titles': {'canonical': 'Joe_Biden',
  'normalized': 'Joe Biden',
  'display': '<span class="mw-page-title-main">Joe Biden</span>'},
 'pageid': 145422,
 'thumbnail': {'source': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/330px-Joe_Biden_presidential_portrait.jpg',
  'width': 330,
  'height': 413},
 'originalimage': {'source': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg',
  'width': 2400,
  'height': 3000},
 'lang': 'en',
 'dir': 'ltr',
 'revision': '1338209404',
 'tid': '84fb6e87-091c-11f1-9d85-0582b5419161',
 'timestamp': '2026-02-13T20:42:32Z',
 'description': 'President of the United States from 2021 to 2025',
 'description_source': 'local',
 'content_urls': {'desktop': {'page': 'https://en.wikipedia.org/wiki/Joe_Biden',
   'revisions': 'https://en.wikipedia.org/wiki/Joe_Biden?action=history',
   'edit': 'https://en.wikipedia.org/wiki/Joe_Biden?action=edit',
   'talk': 'https://en.wikipedia.org/wiki/Talk:Joe_Biden'},
  'mobile': {'page': 'https://en.wikipedia.org/wiki/Joe_Biden',
   'revisions': 'https://en.wikipedia.org/wiki/Special:History/Joe_Biden',
   'edit': 'https://en.wikipedia.org/wiki/Joe_Biden?action=edit',
   'talk': 'https://en.wikipedia.org/wiki/Talk:Joe_Biden'}},
 'extract': 'Joseph Robinette Biden Jr. is an American politician who was the 46th president of the United States from 2021 to 2025. A member of the Democratic Party, he represented Delaware in the United States Senate from 1973 to 2009 and also served as the 47th vice president under President Barack Obama from 2009 to 2017.',
 'extract_html': '<p><b>Joseph Robinette Biden Jr.</b> is an American politician who was the 46th president of the United States from 2021 to 2025. A member of the Democratic Party, he represented Delaware in the United States Senate from 1973 to 2009 and also served as the 47th vice president under President Barack Obama from 2009 to 2017.</p>'}

In [6]:
pd.read_sql('''
    select * from sources
''', conn)

           source_link        created       modified  is_partial
0                  Key  1771107510404  1771107510404           0
1                 Soup  1771107510418  1771107510418           0
2            Star_Trek  1771107510429  1771107510429           0
3                China  1771107510441  1771107510441           0
4           The_Office  1771107510453  1771107510453           0
...                ...            ...            ...         ...
4656      Sogou_Pinyin  1771117911580  1771117911580           0
4657  Friedrich_Engels  1771117911588  1771117911588           0
4658         Mel_Allen  1771117911596  1771117911596           0
4659       Double_play  1771117911605  1771117911605           0
4660    Leshan_dialect  1771117911616  1771117911616           0

[4661 rows x 4 columns]

In [4]:
pd.read_sql('''
    select links.to_link, count(*)
    from links 
    left join sources
        on sources.source_link == links.to_link
    where sources.source_link is null
    group by links.to_link
    order by count(*) desc
    limit 100
''', conn)

                              to_link  count(*)
0                           Wil_Myers       214
1                           Tom_Tresh       201
2                         Eric_Hinske       195
3                     Puroik_language       195
4                      Hruso_language       194
..                                ...       ...
95           Taman_language_(Myanmar)       172
96                        Rich_Gedman       171
97                        Tim_Belcher       171
98  1964_Major_League_Baseball_season       169
99                           Ian_Happ       169

[100 rows x 2 columns]

In [3]:
s = pd.read_sql('''
          
    select *
    from summaries
    order by random()
    limit 1000    
''', conn).sample().iloc[0]

print(s['extract'])
print(s['title'])

The national flag of Canada, popularly referred to as the Maple Leaf, consists of a red field with a white square at its centre in the ratio of 1∶2∶1, in which is featured one stylized, red, 11-pointed maple leaf charged in the centre. It is the first flag to have been adopted by both houses of Parliament and officially proclaimed by the Canadian monarch as the country's official national flag. The flag has become the predominant and most recognizable national symbol of Canada.
Flag of Canada

In [19]:
import pickle

s = pd.read_sql('''
          
    select *
    from embeddings 
''', conn)
s.embedding.apply(lambda x: pickle.loads(x))

0      [0.060689878, 0.05323639, 0.04234263, 0.075609...
1      [0.02588305, -0.0008011006, 0.053584088, 0.098...
2      [-0.023254413, 0.02933463, 0.03757674, 0.00355...
3      [0.015221468, 0.065185316, 0.04403959, 0.02383...
4      [-0.003316514, 0.07554803, -0.02295627, 0.0653...
                             ...
995    [-0.008153627, -0.0057223914, -0.0031914327, 0...
996    [-0.07534776, -0.0067520677, 0.015891118, -0.0...
997    [-0.014982634, 0.009760863, 0.02642908, 0.0065...
998    [-0.024550002, 0.022460693, -0.008100989, -0.0...
999    [-0.017618371, 0.051454928, -0.018885454, 0.02...
Name: embedding, Length: 1000, dtype: object